name: Build CI

on:
  pull_request:
    branches: 
      - "**"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Latest Nightly Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: default
          components: rust-src
    - name: Build the Buildsystem
      run: 
         cargo build --package lightsaber_buildsystem --bins --release
    - name: Copy Buildsystem Binary to Current Working Directory
      run: cp ./target/release/lightbuild ./lightbuild
    - name: Build
      run: echo 1 | ./lightbuild
