name: Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Latest Nightly Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: default
    - uses: actions/checkout@v2
    - name: Build the Buildsystem
      run: 
         cargo build --package lightsaber_buildsystem --bins --release
    - name: Move Buildsystem Binary to Current Working Directory
      run: mv ./target/release/lightbuild . | ls
    - uses: actions/checkout@v2
    - name: Build
      run: echo 1 | ./lightbuild
